### PR TITLE
Make commands look better

### PR DESCRIPTION
**Pull request by chriskuehl**
before:

after:

### CODE REVIEW

**Comment by jvperrin** [comment]
Looks good to me, the one thing I'm not sure about the note in the right sidebar. Do we want to imply that our website is less secure than connecting over SSH? It might be the case, but at the same time, I don't think we need to cast any of our services' security into doubt here. Thoughts?

**Comment by chriskuehl** [comment]
Doesn't matter much to me, I'll change it.

Eventually I hope to destroy commands anyway.

**Comment by jvperrin** [comment]
Sounds good. What would you replace commands with, buttons to create http and mysql spaces and statistics of pages and disk quota?

**Comment by jvperrin** [comment]
(Like individual statistics shown in a sidebar or something when users sign in)

**Comment by chriskuehl** [comment]
something like that, yeah. given that we have logging in already, it's weird to have another page which makes you enter username/password again

**Comment by matthew-mcallister** [comment]
I like the idea of putting shell in a box in an iframe on https://ocf.io/ssh as well.

**Comment by jvperrin** [comment]
Ok, both of those sound like great ideas to me.

**Pull request merged**
