### PR TITLE
optimize svg

### PR DESCRIPTION
**Pull request by nikhiljha**
micro-optimization at its finest, saved a few KB off everything

### CODE REVIEW

**Comment by nikhiljha** [comment]
Screen Shot 2020-06-08 at 3 51 42 PM

Nooo we must save the extra two bytes! Down with `\n` in svg!

**Comment by dkess** [comment]
lmao `python.png` got bigger

**Comment by nikhiljha** [comment]
that one should be an svg anyway, I should look at replacing them

**Comment by ja5087** [comment]
If you run `make install-hooks` it'll run pre-commit before you, well, commit so Jenkins won't get angry.

**Pull request merged**
