### PR TITLE
add option #4 - Slack to IRC documentation

### PR DESCRIPTION
**Pull request by tahabi**
on dkessler's suggestion

### CODE REVIEW

**Comment by dkess** [comment]
Thanks for doing this-- only nitpick is that the line should be wrapped to 80 chars to match the rest of the file (and the rest of the docs).

**Comment by chriskuehl** [comment]
Do we want to advertise this to non-staff?

**Comment by tahabi** [comment]
I guess you did say that a benefit of IRC was the barrier to entry for non-techies, but so few outside of staff even come to IRC via thelounge that I don't think it will be a big deal. Perhaps move this to the staff documentation instead of the user docs?

**Comment by dkess** [comment]
+1 to moving to staff documentation. Slack is really for people who want to stay active in IRC, not people dropping in for a one-time question.

**Comment by chriskuehl** [comment]
> I guess you did say that a benefit of IRC was the barrier to entry for non-techies

heh, i was mostly being facetious

i probably just wouldn't advertise it to non-staff until it's reliably working (currently @jvperrin has to restart the bridge, and it sometimes drops messages)

**Pull request closed without merging**
