### PR TITLE
Daily graph improvements

### PR DESCRIPTION
**Pull request by matthew-mcallister**

### CODE REVIEW

**Comment by jvperrin** [comment]
Screenshot?

**Comment by jvperrin** [comment]
Actually, I think you've described it well enough with the commit names

**Comment by matthew-mcallister** [comment]
It hardly looks different, so I got lazy and didn't upload an image. Here it is though:

screenshot - 11142016 - 04 31 46 pm

**Comment by matthew-mcallister** [comment]
Tests were broken by https://github.com/ocf/ocfweb/commit/ad745e14773465b2a2eda2b1760bf090c50113ac.

**Pull request merged**
