### PR TITLE
Serve static assets from Mesos

### PR DESCRIPTION
**Pull request by chriskuehl**

### CODE REVIEW

**Comment by chriskuehl** [comment]
argh, looks like we hit https://github.com/Yelp/venv-update/issues/150

**Comment by chriskuehl** [comment]
:( :( :( https://issues.jenkins-ci.org/browse/JENKINS-38706

**Comment by chriskuehl** [comment]
i "fixed" it by adding this to the jenkins java options:
```
-Djenkins.branch.WorkspaceLocatorImpl.PATH_MAX=0`
```

...now it's failing because jenkinsfile git clones don't clone submodules apparently

**Comment by jvperrin** [comment]
Nice :D

**Pull request merged**
