### PR TITLE
Vhost form better

### PR DESCRIPTION
**Pull request by chriskuehl**
based on #113 so it has some unrelated changes

### CODE REVIEW

**Comment by jvperrin** [comment]
Looks great! One suggestion I have is to make it clear that *all* the checkboxes are required, because right now unless you submit the form it appears that they are part of the previous section and might be optional. I think just adding a header above the checkboxes like with the other fields and like the [old page](https://github.com/ocf/ocfweb/pull/114/files#diff-9e0f674a5d88014393a30911951bf44aL71) would help to clarify this. It's not much of a problem because if they try to submit the request they will quickly find out that the boxes are not optional, but I think it would help a bit to clear up any potential confusion.

**Comment by chriskuehl** [comment]
@jvperrin okay, added a small label similar to the old form



The commit diff is weird because I can't change the base branch (thanks GitHub), look at 1c637723ba7aafa5bdcda7f5be93a72d5e4513a0 for my change

**Comment by jvperrin** [comment]
@chriskuehl Ok, I think that looks a lot clearer what the checkboxes are for. Ship it!

**Comment by chriskuehl** [comment]
oops merged into wrong branch

**Comment by chriskuehl** [comment]
merged by hand in c24dbdfb82251aa6ec967541c79bea6499a5acee

**Pull request merged**
