### PR TITLE
fix all ocfweb bugs

### PR DESCRIPTION
**Pull request by nikhiljha**
Well folks, I've done it. Bugs are no more. Merge pls.

### CODE REVIEW

**Comment by ja5087** [comment]
image

**Comment by encadyma** [comment]
bruh

**Comment by PotatoParser** [comment]
Bruh

**Comment by BernardZhao** [comment]
bruh

**Comment by bjb568** [comment]
bruh

**Comment by nikhiljha** [comment]
Merged #612 into master.

**Pull request closed without merging**
