### PR TITLE
add non-warranty clause

### PR DESCRIPTION
**Pull request by Baisang**
github is smart and suggested kpengboy as a requestor

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
> github is smart and suggested kpengboy as a requestor

Reviewer?

IANAL but this is cool by me.

**Comment by abizer** [comment]
the RT is real with baisang

**Comment by kpengboy** [comment]
Also don't forget to update the annotation at the top to mention the amendment date

**Comment by Baisang** [comment]
@kpengboy is that date okay? looking at bod minutes it appears to be the date we confirmed the policy during bod

**Comment by kpengboy** [comment]
@Baisang I'll trust that you got the right date

**Pull request merged**
