### PR TITLE
Use datetime.time for lab hours

### PR DESCRIPTION
**Pull request by matthew-mcallister**
This might get in the way of jvperrin's highcharts branch, but it makes sense to do this anyways as we can be more flexible with our hours now if we wish.

### CODE REVIEW

**Comment by chriskuehl** [comment]
This generally looks good, I'll try to comment on your ocflib branch later today

**Comment by matthew-mcallister** [comment]
The build is going to fail, sorry. Depends on the ocflib PR.

**Comment by matthew-mcallister** [comment]
I'm not sure how to actually deploy these two, since each branch will break master on the other repo.

**Comment by chriskuehl** [comment]
@matthew-mcallister you can probably merge the ocflib branch first, tests for ocfweb will hopefully fail and it won't get deployed, then merge this branch.

**Comment by matthew-mcallister** [comment]
OK, that could work.

**Comment by matthew-mcallister** [comment]
retest this please

**Pull request merged**
