### PR TITLE
Updated the former staff page (list of companies and links)

### PR DESCRIPTION
**Pull request by n-patel**
I fixed a lot of broken links -- in some cases, I was able to find the new domain; in other cases, I just removed the link entirely because the company has gone out of business.

Also, note that I linked to the Wikipedia page for Netday '96, as it's a noteworthy event.  (However, I just did a little more poking around, and it seems like they might have merged with http://www.tomorrow.org - I'm not sure.)

### CODE REVIEW

**Comment by matthew-mcallister** [comment]
Nice work, I hope some alum gets to appreciate this page. The only link you missed is the very first one, bmrc.berkeley.edu, which closed in 2002 [[1]](http://vcresearch.berkeley.edu/faculty/lawrence-rowe).

**Comment by chriskuehl** [comment]
Looks great! You can also add LinkedIn if you feel like it, sorry @kennydo

**Comment by kennydo** [comment]
:+1:

**Comment by n-patel** [comment]
@matthew-mcallister Fixed, thanks for the heads-up
@chriskuehl Added LinkedIn

**Comment by chriskuehl** [comment]
sorry, i am low on cat gifs

once you merge you can watch it deploy automatically:
https://jenkins.ocf.berkeley.edu/view/ocfweb-deploy/

**Comment by n-patel** [comment]
Deployed successfully!

**Pull request merged**
