### PR TITLE
Remove "free" before printing

### PR DESCRIPTION
**Pull request by daradib**
I think this is the third time I changed the home page to
just say printing like our other free as in beer services.
This time we have version control. Long live version control.

### CODE REVIEW

**Comment by chriskuehl** [comment]
i'm -0 on this change, i think it's worth mentioning at least once on the home page

**Comment by daradib** [comment]
Should we say "Free web & email hosting" and "Free shell accounts"? I don't see why printing deserves special attention, especially as we are not the Outsourced Copy Facility.

**Comment by chriskuehl** [comment]
think like a regular person: would they charge to use the lab or web hosting? unlikely. but if it doesn't say "free" before printing, many people would expect a charge (think libraries)

**Comment by daradib** [comment]
Lab no, but web hosting maybe. Campus charges for web hosting. Some departments offer free printing and free web hosting.

**Comment by chriskuehl** [comment]
in other words, i think you are trading a fair amount of confusion on the part of people visiting our website for slightly de-emphasizing printing in an insignificant way.

i think our website already does a pretty good job of highlighting the non-printing things we do. if people are reading the website, they'll already see we're more than the Outsourced Copy Facility

**Comment by daradib** [comment]
What about including free on our other services (except computer lab, that's a bit strange):

> A spiffy computer lab in 171 MLK Student Union
> Free web & email hosting for thousands of student groups and individuals
> Free printing for all UC Berkeley students
> Free shell accounts on our powerful on-campus servers
> ...and lots more!

**Comment by daradib** [comment]
@jvperrin @matthew-mcallister @NickImpicciche thoughts - since this is your home page after all?

**Comment by chriskuehl** [comment]
i think that looks kinda silly

the way i see it, there's no benefit to this change besides us patting ourselves on the back a bit, but it will *actually* confuse some nonzero number of people, which is a real negative

**Comment by daradib** [comment]
> A spiffy computer lab in 171 MLK Student Union
> Web & email hosting for thousands of student groups and individuals
> Free printing for all UC Berkeley students
> Shell accounts on our powerful on-campus servers
> ...and lots more!

> A spiffy computer lab in 171 MLK Student Union
> Web & email hosting for thousands of student groups and individuals
> Printing for all UC Berkeley students
> Shell accounts on our powerful on-campus servers
> ...and lots more!

> A spiffy computer lab in 171 MLK Student Union
> Free web & email hosting for thousands of student groups and individuals
> Free printing for all UC Berkeley students
> Free shell accounts on our powerful on-campus servers
> ...and lots more!

To be honest, I think the second looks the best, but maybe it could confuse someone, maybe. For now I'll leave the home page alone and let others decide.

**Comment by chriskuehl** [comment]
what problem are you trying to solve?

**Comment by jvperrin** [comment]
I think keeping free printing listed is fine, I think adding "free" before web and email hosting would be fine too, but I don't think free is something that needs to be said about shell accounts or the lab. I do think we need to mention somewhere that the printing is free, probably multiple places honestly.

Either way I don't think it will matter much, since people already know us mainly for the free printing and lab space and likely won't even notice either way this goes.

**Comment by daradib** [comment]
I left the home page alone. It can be discussed at BoD. @chriskuehl OK with the other two pages?

**Comment by chriskuehl** [comment]
yup lgtm

**Pull request merged**
