### PR TITLE
update SSH host keys for tsunami

### PR DESCRIPTION
**Pull request by cg505**
shows how much these get used

### CODE REVIEW

**Comment by cg505** [comment]
I think they were wrong since we upgraded to buster lol.

**Comment by jvperrin** [comment]
They look the same to me. We place these [from the puppet private share onto disk](https://github.com/ocf/puppet/blob/master/modules/ocf/manifests/hostkeys.pp), so they shouldn't change if tsunami is reprovisioned or anything. I think this change is good though since it adds more hash formats and makes then more consistent across types of keys, but I don't think they were actually _wrong_ before, if that makes sense.

**Comment by cg505** [comment]
Ah, you're right. We didn't have the ed25519 key before and ssh uses sha256 by default now so this is still good to have.

**Comment by cg505** [comment]
Also, I meant to say stretch instead of buster. edited.

**Pull request merged**
