### PR TITLE
Add pages printed per day

### PR DESCRIPTION
**Pull request by chriskuehl**
looks kinda bad, but it's a giant chart, so idk

someone can improve later maybe

i spot-checked that the numbers match stats.ocf.b.e

### CODE REVIEW

**Comment by chriskuehl** [comment]
shoot we need a total column

**Comment by jvperrin** [comment]
Highcharts can make this nicer with a line chart with multiple lines on it, pretty much like the current oracle, but with the page information instead of toner. I think it would look pretty cool anyway, something like this but with printers instead: http://www.highcharts.com/stock/demo/compare

**Comment by chriskuehl** [comment]
i would still want a chart, but a graph is a nice addition

**Comment by jvperrin** [comment]
What's the difference?

**Comment by jvperrin** [comment]
Image vs JS?

**Comment by chriskuehl** [comment]
i don't mind image vs JS, i just want a table of numbers to go along with the fancy graph (that's what i mean by chart in case that was ambiguous)

e.g. on stats.ocf.b.e we almost always use the table rather than the graphs (partially because the graphs are slow and bad, but still, there are some use-cases where a table is better at giving data)

**Comment by chriskuehl** [comment]
i'm all for highcharts or whatever if it means we can get rid of matplotlib and numpy :)

**Comment by jvperrin** [comment]
Oh, sure, I agree on that, I thought you meant some other way of visualizing the data, not a table. I definitely would want to keep around the table, since it's easy to read and has the exact numbers.

I haven't worked on highcharts for a few months now, but it pretty much just needs some helper functions and it'll be good to go. It also needs to be expanded to cope with the large amounts of data it can get, but that shouldn't be terrible, it just involves a readjustment of the periodic functions to not spew out too much data. It would also be nice to be able to look at historical data, but that's a separate project really.

**Pull request merged**
