### PR TITLE
remove unnecessary h_ tag in html ids/quicklinks

### PR DESCRIPTION
**Pull request by tahabi**
With the previous formatting, linking to sections in our docs gives things like this: "https://www.ocf.berkeley.edu/docs/services/vhost/#h4_university-policies". This would make it so links now look like this "https://www.ocf.berkeley.edu/docs/services/vhost/#university-policies" which IMHO is cleaner.

### CODE REVIEW

**Comment by tahabi** [comment]
Of course this breaks all the old links that have already been distributed, but the damage is minimal because the correct page will still load, it just won't jump to the section right away.

**Comment by jvperrin** [comment]
Yeah, that's true, but I think that's fine too. It would be good to grep through all the repos we have to check that there aren't any broken links there though, if you haven't done that already. I did look through templates and short URLs, and I couldn't see any there, but maybe there still are?

**Comment by tahabi** [comment]
Nice catch, there are two places in utils/banner_mass_email.py that use the old link styles. I only have forks of ocfweb, ocflib, utils, puppet, and dns though, but I can't find anything using GitHub code search either.

**Comment by chriskuehl** [comment]
I don't think this is a good idea. It was done for a reason: otherwise it's not clear which headings are considered to have "permanent" IDs that can be reliably linked to, and which are not.

If you undo this, it will become easy for somebody to change a heading in a well-meaning way (e.g. to improve the wording) but to accidentally break a bunch of incoming links in the process. Currently we have no incoming links to the implicit IDs ourselves (and imo we should keep it that way).

We should instead assign actual IDs to headings that we intend to link to, e.g. https://ocf.io/vhost#disclaimer

There's sort of a compromise here: the implicit IDs are nice for referring to things in a non-permanent way (e.g. linking on IRC), but we should really be picking explicit IDs for things we want to link to otherwise.

**Comment by tahabi** [comment]
I don't think it would be a problem to keep this and incrementally add the relevant explicit IDs as well. The informal shortlinks get nice URLs and important things that we link to often we give short, descriptive IDs to as well. fd2ffb0 for example.

**Comment by chriskuehl** [comment]
I still don't think we should do this per my comment above. Why do you want to remove the heading level?

**Comment by Baisang** [comment]
I think "https://www.ocf.berkeley.edu/docs/services/vhost/#h4_university-policies" is just as informative as without the `#h4`. If there aren't common situations where that it will get unreasonably ugly, then I think what @chriskuehl is saying makes more sense. We should just make it explicit when needed.

**Comment by chriskuehl** [comment]
The whole problem is you *can't* tell what you can rely on and what you can't without the heading at the front. If you want to add another way to determine that, that's fine. But right now this PR removes that signal and makes the situation worse.

**Comment by matthew-mcallister** [comment]
I don't really have anything to add here, but I agree with @chriskuehl. This seems like a change for change's sake.

**Pull request closed without merging**
